### ISSUE TITLE
t.filter is not a function

### ISSUE THREAD

**Issue by pun-ky** [kibalabs/github-action-create-annotations#11]
![](https://user-images.githubusercontent.com/10673561/107779987-697efb80-6d46-11eb-8787-b5df7822a457.png)

for config:

```
      - name: Publish Annotation
        uses: kibalabs/github-action-create-annotations@v0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./build/github/annotation.json
          fail-on-error: false
```
